use_frameworks!

platform :ios, '11.0'

target 'ExCoreData_Example' do
  pod 'ExCoreData', :path => '../'

  target 'ExCoreData_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
    
    pod 'ExLog', :git => 'https://github.com/chorokichi/ExLog.git'
  end
end
